version: '3'
services:  
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        networks:
            - backend
        ports:
            - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    chat:
        build:
            context: .
            dockerfile: Dockerfile
        image: chat:latest
        container_name: chat
        restart: always
        networks:
            - backend
        ports:
            - "${SOCKET_SERVER_PORT:-8080}:${SOCKET_SERVER_PORT:-8080}"
        depends_on:
            - redis
        environment:
            - REDIS_HOST=${REDIS_HOST:-redis}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - SOCKET_SERVER_PORT=${SOCKET_SERVER_PORT:-8080}

networks:
    backend: {}